language: cpp
compiler:
 - clang
 - gcc
before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
 - sudo apt-get install
 - sudo apt-get install cmake
 - if [ "$CXX" = "g++" ]; then sudo apt-get install gcc-4.9 g++-4.9; fi
 - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.5; fi
 - sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev
 - sudo apt-get install libx11-dev # libboost-all-dev
 - if [ "$CC" = "gcc" ]; then sudo update-alternatives --set gcc /usr/bin/gcc-4.9; fi
 - if [ "$CC" = "clang" ]; then CXX=/usr/bin/clang-3.5; fi
 - if [ "$CXX" = "g++" ]; then sudo update-alternatives --set g++ /usr/bin/g++-4.9; fi
 - if [ "$CXX" = "clang++" ]; then CXX=/usr/bin/clang++-3.5; fi
 - cmake --version
 - $CC --version
 - $CXX --version
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make
