language: cpp
compiler:
 - clang
 - gcc
before_install:
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
 - sudo apt-get install
 - sudo apt-get install cmake
 - sudo apt-get install g++-4.9
 - sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev
 - sudo apt-get install libx11-dev # libboost-all-dev
 - cmake --version
 - c++ --version
script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..
 - make
